<a href="https://colab.research.google.com/github/rokasta12/Python-Optimization/blob/main/Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing numpy as np
import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

###################

x = np.array([1,2,3])
y = np.array([4,5,6])

#Product of two vectors.
print(np.dot(x,y))

#Transpose of a matrix
print(np.transpose(A))

#Creating identity matrix 
print(np.eye(3))


#Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:

a1= np.array([[3,1], [1,2]])
b1 = np.array([9,8])
x1 = np.linalg.solve(a1, b1)
print(x1)


#Eigenvalues

results = np.linalg.eig(A)
print(results)

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]
32
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2. 3.]
(array([11.24862343,  5.09285054, -5.34147398]), array([[ 0.24511338,  0.75669314,  0.02645665],
       [ 0.40622202, -0.03352363, -0.84078293],
       [ 0.88028581, -0.65291014,  0.54072554]]))
